package com.domo.mock;

import com.domo.post.domain.Post;
import com.domo.post.service.port.PostRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakePostRepository implements PostRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Post> posts = new ArrayList<>();

    @Override
    public Optional<Post> findById(long id) {
        return posts.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public Post save(Post post) {
        if (post.getId() == null || post.getId() == 0) {
            Post newPost = Post.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .content(post.getContent())
                    .writer(post.getWriter())
                    .createdAt(post.getCreatedAt())
                    .modifiedAt(post.getModifiedAt())
                    .build();
            posts.add(post);
            return newPost;
        } else {
            Post finalPost = post;
            posts.removeIf(item -> Objects.equals(item.getId(), finalPost.getId()));
            posts.add(post);
            return post;
        }
    }
}
