package com.depromeet.yunbeom.mock;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

import com.depromeet.yunbeom.post.domain.Post;
import com.depromeet.yunbeom.post.service.port.PostRepository;

public class FakePostRepository implements PostRepository {
	private final AtomicLong autoGeneratedId = new AtomicLong(0);
	private final List<Post> data = Collections.synchronizedList(new ArrayList<>());

	@Override
	public Optional<Post> findById(long id) {
		return data.stream().filter(item -> item.getId().equals(id)).findAny();
	}

	@Override
	public Post save(Post post) {
		/**
		 * id가 null이거나 0이면 새로운 게시물을 생성하고, 그렇지 않으면 기존 게시물을 수정한다.
		 */
		if (post.getId() == null || post.getId() == 0) {
			Post newPost = Post.builder()
				.id(autoGeneratedId.incrementAndGet())
				.content(post.getContent())
				.createdAt(post.getCreatedAt())
				.modifiedAt(post.getModifiedAt())
				.writer(post.getWriter())
				.build();
			data.add(newPost);
			return newPost;
		} else {
			data.removeIf(item -> Objects.equals(item.getId(), post.getId()));
			data.add(post);
			return post;
		}
	}
}
